version: '3'
services:
  app:
    build: .
    command: sh -c "yarn start:dev"
    volumes:
      - .:/myapp
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    volumes:
      - ./data/db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

