version: '3'
services:
  app:
    build: .
    command: sh -c "yarn start:dev"
    volumes:
      - .:/myapp
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    #environment:
    #    MONGO_INITDB_ROOT_USERNAME: root
    #    MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: password

